# Generated by Django 5.1.3 on 2024-11-24 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WorkerModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uname', models.CharField(max_length=100)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=100)),
                ('phone', models.PositiveIntegerField()),
                ('district', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('pin', models.PositiveIntegerField()),
                ('skills', models.CharField(choices=[('plumber', 'Plumber'), ('electrician', 'Electrician'), ('cleaner', 'Cleaner'), ('gardener', 'Gardener'), ('carpenter', 'Carpenter'), ('painter', 'Painter'), ('welder', 'Welder'), ('mechanic', 'Mechanic'), ('cook', 'Cook'), ('driver', 'Driver')], max_length=100)),
                ('certification', models.FileField(blank=True, null=True, upload_to='certificates/')),
                ('is_approved', models.BooleanField(default=False)),
            ],
        ),
    ]
