# Generated by Django 5.1.3 on 2024-11-24 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_app', '0002_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='is_accepted',
            field=models.BooleanField(default=False),
        ),
    ]
