# Generated by Django 5.1.3 on 2024-11-25 01:38

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service_app', '0003_job_is_accepted'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Job',
            new_name='JobModel',
        ),
    ]
