# Generated by Django 5.1.3 on 2024-11-25 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_app', '0004_rename_job_jobmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobmodel',
            name='skill',
            field=models.CharField(choices=[('plumber', 'Plumber'), ('electrician', 'Electrician'), ('cleaner', 'Cleaner'), ('gardener', 'Gardener'), ('carpenter', 'Carpenter'), ('painter', 'Painter'), ('welder', 'Welder'), ('mechanic', 'Mechanic'), ('cook', 'Cook'), ('driver', 'Driver')], max_length=100, null=True),
        ),
    ]
