# Generated by Django 5.1.3 on 2024-11-26 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_app', '0005_jobmodel_skill'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobmodel',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pictures/'),
        ),
    ]
