# Generated by Django 5.1.3 on 2024-11-26 23:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service_app', '0006_jobmodel_profile_picture'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workermodel',
            old_name='city',
            new_name='location',
        ),
        migrations.RemoveField(
            model_name='workermodel',
            name='district',
        ),
    ]
