# Generated by Django 5.1.3 on 2024-11-27 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_app', '0007_rename_city_workermodel_location_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobmodel',
            name='profile_picture',
        ),
        migrations.AddField(
            model_name='workermodel',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pictures/'),
        ),
    ]
