# Generated by Django 5.1.3 on 2024-12-03 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service_app', '0009_workermodel_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workermodel',
            name='user',
        ),
        migrations.DeleteModel(
            name='JobModel',
        ),
        migrations.DeleteModel(
            name='WorkerModel',
        ),
    ]
