# Generated by Django 5.1.3 on 2024-12-09 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_app', '0011_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workermodel',
            name='registered_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
