# Generated by Django 5.1.3 on 2024-12-09 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_app', '0012_workermodel_registered_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobmodel',
            name='applicants',
            field=models.ManyToManyField(blank=True, related_name='job_applications', to='service_app.workermodel'),
        ),
    ]
