# Generated by Django 5.1.3 on 2024-12-10 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_app', '0013_jobmodel_applicants'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobmodel',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('completed', 'Completed')], default='pending', max_length=20),
        ),
    ]
